# Этап сборки
FROM golang:1.21-alpine AS builder

WORKDIR /app

# Копируем go.mod и go.sum
COPY go.mod go.sum ./

RUN go mod download

# Копируем исходники
COPY cmd/worker/ ./cmd/worker/

# Сборка бинарника
RUN CGO_ENABLED=0 GOOS=linux go build -o worker ./cmd/worker

# Этап выполнения
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/worker .

CMD ["./worker"]